@startuml DER-Cupcakes
hide circle
skinparam linetype ortho

entity usuario {
  * id : BIGSERIAL <<PK>>
  --
  * nome : VARCHAR(100)
  * sobrenome : VARCHAR(100)
  * telefone : VARCHAR(11)
  * email : VARCHAR(150) <<UNIQUE>>
  * senha_hash : VARCHAR(100)
  * perfil : VARCHAR(20)
  * tentativas_falhas : INT
    bloqueado_ate : TIMESTAMP
  * criado_em : TIMESTAMP
  * atualizado_em : TIMESTAMP
}

entity endereco {
  * id : BIGSERIAL <<PK>>
  --
  * usuario_id : BIGINT <<FK>>
  * logradouro : VARCHAR(100)
  * numero : VARCHAR(10)
  * cep : CHAR(8)
   complemento : VARCHAR(50)
  * bairro : VARCHAR(50)
  * cidade : VARCHAR(50)
  * uf : VARCHAR(2)
  * padrao: BOOLEAN
  * criado_em : TIMESTAMP
  * atualizado_em : TIMESTAMP
}

entity categoria {
  * id : BIGSERIAL <<PK>>
  --
  * nome : VARCHAR(100) <<UNIQUE>>
  * criado_em : TIMESTAMP
  * atualizado_em : TIMESTAMP
}

entity produto {
  * id : BIGSERIAL <<PK>>
  --
  * categoria_id : BIGINT <<FK>>
  * nome : VARCHAR(100)
  * descricao : VARCHAR(200)
  * estoque : INT
  * preco : DECIMAL(10,2)
  * foto_url : VARCHAR(255)
  * ativo : BOOLEAN
  * criado_em : TIMESTAMP
  * atualizado_em : TIMESTAMP
}

entity pedido {
  * id : BIGSERIAL <<PK>>
  --
  * usuario_id : BIGINT <<FK>>
  * numero: VARCHAR(20) <<UNIQUE>>
  * total: DECIMAL(10,2)
  * subtotal: DECIMAL(10,2)
  * frete : DECIMAL(10,2)
  * status : VARCHAR(50)
  * entrega_logradouro : VARCHAR(100)
  * entrega_numero : VARCHAR(10)
  * entrega_cep : CHAR(8)
   entrega_complemento : VARCHAR(50)
  * entrega_bairro : VARCHAR(50)
  * entrega_cidade : VARCHAR(50)
  * entrega_uf : VARCHAR(2)
  * criado_em : TIMESTAMP
  * atualizado_em : TIMESTAMP
}

entity item_pedido {
  * id : BIGSERIAL <<PK>>
  --
  * pedido_id : BIGINT <<FK>>
  * produto_id : BIGINT <<FK>>
  * quantidade : INT
  * preco_unitario : DECIMAL(10,2)
  * criado_em : TIMESTAMP
}

entity pagamento {
  * id : BIGSERIAL <<PK>>
  --
  * pedido_id : BIGINT <<FK, UNIQUE>>
  * forma : VARCHAR(50)
  * status : VARCHAR(50)
  * valor : DECIMAL(10,2)
   bandeira : VARCHAR(50)
   ultimos_digitos : CHAR(5)
   pix_copia_cola : VARCHAR(512)
   pix_expira_em : TIMESTAMP
  * criado_em : TIMESTAMP
  * atualizado_em : TIMESTAMP
}

entity token_redefinicao_senha {
  * id : BIGSERIAL <<PK>>
  --
  * usuario_id : BIGINT <<FK>>
  * token_hash : VARCHAR(100) <<UNIQUE>>
  * criado_em : TIMESTAMP
  * expira_em : TIMESTAMP
   usado_em : TIMESTAMP
}

usuario   ||--o{ endereco                : possui
usuario   ||--o{ pedido                  : realiza
usuario   ||--o{ token_redefinicao_senha : solicita
categoria ||--o{ produto                 : agrupa
pedido    ||--|{ item_pedido             : contém
produto   ||--o{ item_pedido             : aparece em
pedido    ||--o| pagamento               : é pago por
@enduml
