-- =========================================================
-- V1 - Esquema inicial (projeto físico do DER)
-- =========================================================

CREATE TABLE usuario (
                       id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nome               VARCHAR(100) NOT NULL,
                       sobrenome          VARCHAR(100) NOT NULL,
                       telefone           VARCHAR(11)  NOT NULL,
                       email              VARCHAR(150) NOT NULL,
                       senha_hash         VARCHAR(100) NOT NULL,
                       perfil             VARCHAR(20)  DEFAULT 'CLIENTE' NOT NULL,
                       tentativas_falhas  INT          DEFAULT 0 NOT NULL,
                       bloqueado_ate      TIMESTAMP,
                       criado_em          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       atualizado_em      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       CONSTRAINT uk_usuario_email      UNIQUE (email),
                       CONSTRAINT ck_usuario_perfil     CHECK (perfil IN ('CLIENTE', 'ADMIN')),
                       CONSTRAINT ck_usuario_tentativas CHECK (tentativas_falhas >= 0)
);

CREATE TABLE endereco (
                        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        usuario_id    BIGINT       NOT NULL,
                        logradouro    VARCHAR(100) NOT NULL,
                        numero        VARCHAR(10)  NOT NULL,
                        cep           CHAR(8)      NOT NULL,
                        complemento   VARCHAR(50),
                        bairro        VARCHAR(50)  NOT NULL,
                        cidade        VARCHAR(50)  NOT NULL,
                        uf            VARCHAR(2)   NOT NULL,
                        padrao        BOOLEAN      DEFAULT FALSE NOT NULL,
                        criado_em     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        atualizado_em TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        CONSTRAINT fk_endereco_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);
CREATE INDEX idx_endereco_usuario ON endereco (usuario_id);

CREATE TABLE categoria (
                         id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome          VARCHAR(100) NOT NULL,
                         criado_em     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         atualizado_em TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT uk_categoria_nome UNIQUE (nome)
);

CREATE TABLE produto (
                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       categoria_id  BIGINT        NOT NULL,
                       nome          VARCHAR(100)  NOT NULL,
                       descricao     VARCHAR(200)  NOT NULL,
                       estoque       INT           DEFAULT 0 NOT NULL,
                       preco         DECIMAL(10,2) NOT NULL,
                       foto_url      VARCHAR(255)  NOT NULL,
                       ativo         BOOLEAN       DEFAULT TRUE NOT NULL,
                       criado_em     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       atualizado_em TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       CONSTRAINT fk_produto_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (id),
                       CONSTRAINT ck_produto_preco   CHECK (preco > 0),
                       CONSTRAINT ck_produto_estoque CHECK (estoque >= 0)
);
CREATE INDEX idx_produto_categoria ON produto (categoria_id);
CREATE INDEX idx_produto_nome      ON produto (nome);

CREATE TABLE pedido (
                      id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      usuario_id          BIGINT        NOT NULL,
                      numero              VARCHAR(20)   NOT NULL,
                      subtotal            DECIMAL(10,2) NOT NULL,
                      frete               DECIMAL(10,2) NOT NULL,
                      total               DECIMAL(10,2) NOT NULL,
                      status              VARCHAR(50)   NOT NULL,
                      entrega_logradouro  VARCHAR(100)  NOT NULL,
                      entrega_numero      VARCHAR(10)   NOT NULL,
                      entrega_cep         CHAR(8)       NOT NULL,
                      entrega_complemento VARCHAR(50),
                      entrega_bairro      VARCHAR(50)   NOT NULL,
                      entrega_cidade      VARCHAR(50)   NOT NULL,
                      entrega_uf          VARCHAR(2)    NOT NULL,
                      criado_em           TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      atualizado_em       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      CONSTRAINT uk_pedido_numero  UNIQUE (numero),
                      CONSTRAINT fk_pedido_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
                      CONSTRAINT ck_pedido_valores CHECK (subtotal >= 0 AND frete >= 0 AND total >= 0),
                      CONSTRAINT ck_pedido_status  CHECK (status IN ('AGUARDANDO_PAGAMENTO', 'PAGO', 'EM_PREPARO',
                                                                     'SAIU_PARA_ENTREGA', 'ENTREGUE', 'CANCELADO'))
);
CREATE INDEX idx_pedido_usuario ON pedido (usuario_id);
CREATE INDEX idx_pedido_status  ON pedido (status);

CREATE TABLE item_pedido (
                           id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           pedido_id      BIGINT        NOT NULL,
                           produto_id     BIGINT        NOT NULL,
                           quantidade     INT           NOT NULL,
                           preco_unitario DECIMAL(10,2) NOT NULL,
                           criado_em      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           CONSTRAINT fk_item_pedido  FOREIGN KEY (pedido_id)  REFERENCES pedido (id) ON DELETE CASCADE,
                           CONSTRAINT fk_item_produto FOREIGN KEY (produto_id) REFERENCES produto (id),
                           CONSTRAINT ck_item_quantidade CHECK (quantidade BETWEEN 1 AND 50),
                           CONSTRAINT ck_item_preco      CHECK (preco_unitario > 0)
);
CREATE INDEX idx_item_pedido ON item_pedido (pedido_id);

CREATE TABLE pagamento (
                         id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         pedido_id       BIGINT        NOT NULL,
                         forma           VARCHAR(50)   NOT NULL,
                         status          VARCHAR(50)   NOT NULL,
                         valor           DECIMAL(10,2) NOT NULL,
                         bandeira        VARCHAR(50),
                         ultimos_digitos CHAR(4),
                         pix_copia_cola  VARCHAR(512),
                         pix_expira_em   TIMESTAMP,
                         criado_em       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         atualizado_em   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT uk_pagamento_pedido   UNIQUE (pedido_id),
                         CONSTRAINT fk_pagamento_pedido   FOREIGN KEY (pedido_id) REFERENCES pedido (id),
                         CONSTRAINT ck_pagamento_forma    CHECK (forma IN ('CARTAO_CREDITO', 'CARTAO_DEBITO', 'PIX')),
                         CONSTRAINT ck_pagamento_status   CHECK (status IN ('PENDENTE', 'APROVADO', 'RECUSADO', 'EXPIRADO')),
                         CONSTRAINT ck_pagamento_bandeira CHECK (bandeira IS NULL OR bandeira IN ('VISA', 'MASTERCARD', 'ELO'))
);

CREATE TABLE token_redefinicao_senha (
                                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       usuario_id BIGINT       NOT NULL,
                                       token_hash VARCHAR(100) NOT NULL,
                                       criado_em  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                       expira_em  TIMESTAMP    NOT NULL,
                                       usado_em   TIMESTAMP,
                                       CONSTRAINT uk_token_hash    UNIQUE (token_hash),
                                       CONSTRAINT fk_token_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);
CREATE INDEX idx_token_usuario ON token_redefinicao_senha (usuario_id);
